"""Generate docs/annotation_guideline.md from LabelScheme (definitions, guidance, examples).

Edit label wording in backend/app/annotation/label_scheme.py, then re-run this script.
A test fails if the committed guideline and LabelScheme disagree.

Usage (from the repo root):  python backend/scripts/build_guideline.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.annotation.label_scheme import LabelScheme  # noqa: E402
from app.config import REPO_ROOT  # noqa: E402

GUIDELINE_PATH = REPO_ROOT / "docs" / "annotation_guideline.md"

INTRO = """# Rhetorical-Role Annotation Guideline

<!-- Generated by backend/scripts/build_guideline.py from backend/app/annotation/label_scheme.py.
     Do not edit by hand: change LabelScheme and re-run the script. -->

You will label every sentence of a criminal judgment with the **rhetorical role** it plays.
These labels train the Phase 3 classifier and form the gold corpus for fine-tuning, so
consistency matters more than speed.

## How to annotate

1. Open the **Annotate** tab, enter your name (it is stored with every label), and pick a case.
2. Read the whole judgment once before labelling, so you know who is speaking where.
3. Label each sentence with one role. Keys **{shortcuts}** assign a label and move to the next
   sentence; **↑/↓** (or **k/j**) move; **n** jumps to the next unlabelled sentence. Labels save
   immediately.
4. Judge each sentence **by its function in the judgment**, not by its topic: a sentence that
   mentions Section 302 can be Facts, Law Applied, Argument or Ruling depending on who says it
   and why.
5. When unsure between two roles, use the decision rules below. If still unsure, pick the
   better fit and note the sentence for discussion — do not leave it unlabelled.

### Tie-break order

If a sentence genuinely fits more than one role, choose the first that applies:
**Ruling > Argument > Precedent > Law Applied > Facts**. This is the order the team used for
the seed corpus (`legaltech_dataset.xlsx`), so keep it for consistency. *None* is outside this
order: use it only when no role fits at all.

### Decision rules for common confusions

- **Who is speaking?** Counsel's submissions are *Argument* even when they recite facts or law.
  The court's own evaluation is *Ruling*.
- **Law in general vs. law applied here.** Stating what a section says or requires is
  *Law Applied*; concluding that its ingredients are (or are not) met on these facts is *Ruling*.
- **Where does the legal principle come from?** From a statute: *Law Applied*. From an earlier
  judgment: *Precedent*.
- **Narrating vs. deciding facts.** Recounting the prosecution story or lower-court history is
  *Facts*; the court's finding on what actually happened ("we find that…") is *Ruling*.

### Double annotation

To validate this guideline, some cases are labelled independently by two people. The UI only
ever shows you your own labels. Agreement is measured with Cohen's kappa
(`python backend/scripts/annotation_agreement.py <you> <colleague>`); disagreements are
discussed and the guideline is updated before labelling scales up. The last label saved for a
sentence becomes the gold label, so adjudication is simply re-labelling the sentence.

## Labels
"""


def render() -> str:
    shortcuts = "/".join(LabelScheme.definition(label).shortcut for label in LabelScheme.LABELS)
    parts = [INTRO.format(shortcuts=shortcuts)]
    for label in LabelScheme.LABELS:
        d = LabelScheme.definition(label)
        parts.append(f"\n### {d.shortcut} · {d.name}\n")
        parts.append(f"**Definition.** {LabelScheme.describe(label)}\n")
        parts.append(f"**How to apply.** {d.guidance}\n")
        parts.append("**Examples** (representative sentences, not quotations):\n")
        parts.extend(f"- {ex}" for ex in d.examples)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    GUIDELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
    GUIDELINE_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {GUIDELINE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
